name: RSpec

on:
  push:
    branches:
      - "*"

jobs:
  rspec:
    runs-on: ubuntu-latest
    services:

    steps:
      - name: Checking out repository
        uses: actions/checkout@v2

      - name: Setting up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: rspec
        run: bundle exec rspec
